// Code generated by scripts/generate-website-name-defaults.mjs from shared/website-name-defaults.json. DO NOT EDIT.
package setting

const (
	WebsiteNameGroup      = "website_name"
	WebsiteNameKeyStatus  = "website_name_status"
	WebsiteNameKeyIntro   = "website_name_intro"
	WebsiteNameKeyEyebrow = "website_name_eyebrow"
	WebsiteNameKeyTitle   = "website_name_title"
	WebsiteNameKeyBody    = "website_name_body"
	WebsiteNameKeyNote    = "website_name_note"
)

func WebsiteNameSettingDescription(key string) string {
	switch key {
	case WebsiteNameKeyStatus:
		return "Why this name page: status"
	case WebsiteNameKeyIntro:
		return "Why this name page: intro"
	case WebsiteNameKeyEyebrow:
		return "Why this name page: eyebrow"
	case WebsiteNameKeyTitle:
		return "Why this name page: title"
	case WebsiteNameKeyBody:
		return "Why this name page: body"
	case WebsiteNameKeyNote:
		return "Why this name page: note"
	default:
		return key
	}
}

var websiteNameDefaultSettingsByLocale = map[string]WebsiteNameSettings{
	"en": {
		Locale:  "en",
		Status:  "Website context",
		Intro:   "This page will explain the working relationship behind this website before describing why I use the name “Me & This Website”.",
		Eyebrow: "WHY THIS NAME",
		Title:   "Why This Name",
		Body:    "",
		Note:    "",
	},
	"zh_cn": {
		Locale:  "zh_cn",
		Status:  "网站说明",
		Intro:   "这里会先说明这个网站背后的工作关系，再继续解释我为什么使用“Me & This Website”这个名字。",
		Eyebrow: "WHY THIS NAME",
		Title:   "为什么叫这个名字",
		Body:    "",
		Note:    "",
	},
}
