-- Retired G35 catalog seed.
--
-- Product rows, SKU variants, media, and product-specific values must come
-- only from the admin product workflow. Keeping this migration as a no-op
-- preserves the contiguous migration history while preventing a fresh
-- deployment or manual rerun from creating hidden catalog data.
