ALTER TABLE product_categories
    ADD COLUMN IF NOT EXISTS meta_title VARCHAR(160) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS meta_description TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS seo_intro TEXT NOT NULL DEFAULT '';

ALTER TABLE product_category_translations
    ADD COLUMN IF NOT EXISTS meta_title VARCHAR(160) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS meta_description TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS seo_intro TEXT NOT NULL DEFAULT '';
