ALTER TABLE currency_exchange_rates ALTER COLUMN rate TYPE DOUBLE PRECISION;
ALTER TABLE orders
    ALTER COLUMN subtotal_amount TYPE DOUBLE PRECISION,
    ALTER COLUMN shipping_fee TYPE DOUBLE PRECISION,
    ALTER COLUMN tax_amount TYPE DOUBLE PRECISION,
    ALTER COLUMN discount_amount TYPE DOUBLE PRECISION,
    ALTER COLUMN total_amount TYPE DOUBLE PRECISION,
    ALTER COLUMN points_value TYPE DOUBLE PRECISION;
ALTER TABLE gift_card_transactions DROP COLUMN IF EXISTS currency;
