-- Persist the normalized IP-network signal used by the referral binding cap.
-- The raw IP is never stored; both values are HMACs generated by the service.
ALTER TABLE referral_records
    ADD COLUMN IF NOT EXISTS client_ip_subnet_hash VARCHAR(64) NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_referral_records_ip_subnet_created
    ON referral_records(client_ip_subnet_hash, created_at DESC)
    WHERE client_ip_subnet_hash <> '';
