INSERT INTO email_templates (
    code,
    locale,
    category,
    name,
    subject_template,
    body_html,
    body_text,
    allowed_variables,
    required_variables,
    is_enabled,
    version
)
VALUES
    ('order_confirmation', 'en', 'order', 'Order confirmation',
        'Order {{order_number}} confirmed',
        '<p>Thank you for your order <strong>{{order_number}}</strong>.</p><p>Total: {{order_amount}}.</p><p>Paid at: {{paid_at}}.</p>',
        'Thank you for your order {{order_number}}.\nTotal: {{order_amount}}.\nPaid at: {{paid_at}}.',
        '["order_number","order_amount","paid_at","customer_name","currency","items"]'::jsonb,
        '["order_number","order_amount","paid_at"]'::jsonb,
        TRUE, 1),
    ('order_payment_expired', 'en', 'order', 'Payment expired',
        'Payment window expired for {{order_number}}',
        '<p>The payment window for order <strong>{{order_number}}</strong> has expired.</p>',
        'The payment window for order {{order_number}} has expired.',
        '["order_number","customer_name","expired_at"]'::jsonb,
        '["order_number"]'::jsonb,
        TRUE, 1),
    ('order_cancelled', 'en', 'order', 'Order cancelled',
        'Order {{order_number}} cancelled',
        '<p>Order <strong>{{order_number}}</strong> has been cancelled.</p>',
        'Order {{order_number}} has been cancelled.',
        '["order_number","customer_name","cancelled_at","cancellation_reason"]'::jsonb,
        '["order_number"]'::jsonb,
        TRUE, 1),
    ('order_shipping_notification', 'en', 'order', 'Order shipping notification',
        'Order {{order_number}} has shipped',
        '<p>Order <strong>{{order_number}}</strong> has shipped with {{carrier_name}}.</p><p>Tracking: {{tracking_number}}</p><p>{{tracking_url}}</p>',
        'Order {{order_number}} has shipped with {{carrier_name}}.\nTracking: {{tracking_number}}\n{{tracking_url}}',
        '["order_number","carrier_name","tracking_number","tracking_url","customer_name","shipped_at","items"]'::jsonb,
        '["order_number","carrier_name","tracking_number","tracking_url"]'::jsonb,
        TRUE, 1),
    ('order_delivered', 'en', 'order', 'Order delivered',
        'Order {{order_number}} delivered',
        '<p>Order <strong>{{order_number}}</strong> was delivered at {{delivered_at}}.</p>',
        'Order {{order_number}} was delivered at {{delivered_at}}.',
        '["order_number","delivered_at","customer_name","tracking_number"]'::jsonb,
        '["order_number","delivered_at"]'::jsonb,
        TRUE, 1),
    ('order_completed', 'en', 'order', 'Order completed',
        'Order {{order_number}} completed',
        '<p>Order <strong>{{order_number}}</strong> is now complete.</p>',
        'Order {{order_number}} is now complete.',
        '["order_number","completed_at","customer_name"]'::jsonb,
        '["order_number","completed_at"]'::jsonb,
        TRUE, 1),
    ('order_refunded', 'en', 'order', 'Order refund completed',
        'Refund completed for {{order_number}}',
        '<p>The refund for order <strong>{{order_number}}</strong> is complete.</p><p>Refund amount: {{refund_amount}} {{currency}}.</p>',
        'The refund for order {{order_number}} is complete.\nRefund amount: {{refund_amount}} {{currency}}.',
        '["order_number","refund_amount","currency","customer_name","refunded_at","refund_reason"]'::jsonb,
        '["order_number","refund_amount","currency"]'::jsonb,
        TRUE, 1),
    ('after_sales_requested', 'en', 'after_sales', 'After-sales request received',
        'After-sales request {{after_sales_case_number}} received',
        '<p>We received after-sales request <strong>{{after_sales_case_number}}</strong> for order {{order_number}}.</p><p>Status: {{after_sales_status}}.</p>',
        'We received after-sales request {{after_sales_case_number}} for order {{order_number}}.\nStatus: {{after_sales_status}}.',
        '["after_sales_case_number","order_number","after_sales_type","after_sales_status","customer_name","requested_at"]'::jsonb,
        '["after_sales_case_number","order_number","after_sales_type","after_sales_status"]'::jsonb,
        TRUE, 1),
    ('after_sales_approved', 'en', 'after_sales', 'After-sales request approved',
        'After-sales request {{after_sales_case_number}} approved',
        '<p>After-sales request <strong>{{after_sales_case_number}}</strong> has been approved.</p><p>Status: {{after_sales_status}}.</p>',
        'After-sales request {{after_sales_case_number}} has been approved.\nStatus: {{after_sales_status}}.',
        '["after_sales_case_number","after_sales_type","after_sales_status","customer_name","approved_at","next_step"]'::jsonb,
        '["after_sales_case_number","after_sales_type","after_sales_status"]'::jsonb,
        TRUE, 1),
    ('after_sales_awaiting_return', 'en', 'after_sales', 'After-sales return instructions',
        'Return instructions for {{after_sales_case_number}}',
        '<p>Please return the item for case <strong>{{after_sales_case_number}}</strong> to {{return_warehouse_name}}.</p><p>{{return_warehouse_address}}</p>',
        'Please return the item for case {{after_sales_case_number}} to {{return_warehouse_name}}.\n{{return_warehouse_address}}',
        '["after_sales_case_number","return_warehouse_name","return_warehouse_address","customer_name","return_deadline"]'::jsonb,
        '["after_sales_case_number","return_warehouse_name","return_warehouse_address"]'::jsonb,
        TRUE, 1),
    ('after_sales_return_in_transit', 'en', 'after_sales', 'After-sales return in transit',
        'Return for {{after_sales_case_number}} is in transit',
        '<p>Return case <strong>{{after_sales_case_number}}</strong> is in transit with {{carrier_name}}.</p><p>Tracking: {{tracking_number}}</p><p>{{tracking_url}}</p>',
        'Return case {{after_sales_case_number}} is in transit with {{carrier_name}}.\nTracking: {{tracking_number}}\n{{tracking_url}}',
        '["after_sales_case_number","carrier_name","tracking_number","tracking_url","customer_name","shipped_at"]'::jsonb,
        '["after_sales_case_number","carrier_name","tracking_number","tracking_url"]'::jsonb,
        TRUE, 1),
    ('after_sales_received', 'en', 'after_sales', 'After-sales return received',
        'Return received for {{after_sales_case_number}}',
        '<p>We received the return for case <strong>{{after_sales_case_number}}</strong> at {{received_at}}.</p>',
        'We received the return for case {{after_sales_case_number}} at {{received_at}}.',
        '["after_sales_case_number","received_at","customer_name","carrier_name","tracking_number"]'::jsonb,
        '["after_sales_case_number","received_at"]'::jsonb,
        TRUE, 1),
    ('after_sales_resolving', 'en', 'after_sales', 'After-sales case resolving',
        'After-sales case {{after_sales_case_number}} is being resolved',
        '<p>Case <strong>{{after_sales_case_number}}</strong> is now being resolved.</p><p>Status: {{after_sales_status}}.</p>',
        'Case {{after_sales_case_number}} is now being resolved.\nStatus: {{after_sales_status}}.',
        '["after_sales_case_number","after_sales_status","customer_name","resolution_note"]'::jsonb,
        '["after_sales_case_number","after_sales_status"]'::jsonb,
        TRUE, 1),
    ('after_sales_completed', 'en', 'after_sales', 'After-sales case completed',
        'After-sales case {{after_sales_case_number}} completed',
        '<p>Case <strong>{{after_sales_case_number}}</strong> is complete.</p><p>Status: {{after_sales_status}}. Refund: {{refund_amount}}.</p>',
        'Case {{after_sales_case_number}} is complete.\nStatus: {{after_sales_status}}. Refund: {{refund_amount}}.',
        '["after_sales_case_number","after_sales_status","refund_amount","customer_name","completed_at","resolution"]'::jsonb,
        '["after_sales_case_number","after_sales_status","refund_amount"]'::jsonb,
        TRUE, 1),
    ('after_sales_rejected', 'en', 'after_sales', 'After-sales request rejected',
        'After-sales request {{after_sales_case_number}} rejected',
        '<p>After-sales request <strong>{{after_sales_case_number}}</strong> was rejected.</p><p>Reason: {{rejection_reason}}.</p>',
        'After-sales request {{after_sales_case_number}} was rejected.\nReason: {{rejection_reason}}.',
        '["after_sales_case_number","rejection_reason","customer_name","rejected_at"]'::jsonb,
        '["after_sales_case_number","rejection_reason"]'::jsonb,
        TRUE, 1)
ON CONFLICT (code, locale) DO NOTHING;

-- Keep the immutable audit history aligned with the seeded current rows. The
-- insert is idempotent so re-running migrations never creates duplicate
-- version-one snapshots and edited templates are left untouched.
INSERT INTO email_template_versions (
    template_id,
    code,
    locale,
    version,
    name,
    subject_template,
    body_html,
    body_text,
    allowed_variables,
    required_variables,
    change_reason
)
SELECT
    t.id,
    t.code,
    t.locale,
    t.version,
    t.name,
    t.subject_template,
    t.body_html,
    t.body_text,
    t.allowed_variables,
    t.required_variables,
    'initial transactional notification template seed'
FROM email_templates AS t
WHERE t.locale = 'en'
  AND t.version = 1
  AND t.code IN (
      'order_confirmation',
      'order_payment_expired',
      'order_cancelled',
      'order_shipping_notification',
      'order_delivered',
      'order_completed',
      'order_refunded',
      'after_sales_requested',
      'after_sales_approved',
      'after_sales_awaiting_return',
      'after_sales_return_in_transit',
      'after_sales_received',
      'after_sales_resolving',
      'after_sales_completed',
      'after_sales_rejected'
  )
ON CONFLICT (template_id, version) DO NOTHING;
