// Code generated by scripts/generate-website-name-defaults.mjs from shared/website-name-defaults.json. DO NOT EDIT.

export interface WebsiteNameDefaultValues {
  status: string
  intro: string
  eyebrow: string
  title: string
  body: string
  note: string
}

export type WebsiteNameDefaultLocale = 'en' | 'zh_cn'

export const WEBSITE_NAME_DEFAULTS: Record<WebsiteNameDefaultLocale, WebsiteNameDefaultValues> = {
  en: {
    status: "Website context",
    intro: "This page will explain the working relationship behind this website before describing why I use the name “Me & This Website”.",
    eyebrow: "WHY THIS NAME",
    title: "Why This Name",
    body: "",
    note: "",
  },
  zh_cn: {
    status: "网站说明",
    intro: "这里会先说明这个网站背后的工作关系，再继续解释我为什么使用“Me & This Website”这个名字。",
    eyebrow: "WHY THIS NAME",
    title: "为什么叫这个名字",
    body: "",
    note: "",
  },
}
