package service

import (
	"errors"

	"commerce-platform/internal/domain/order"
	"commerce-platform/internal/pkg/email"
	"commerce-platform/internal/pkg/ordernumber"
	"commerce-platform/internal/repository"
)

type OrderService struct {
	txManager          *repository.TxManager
	orderRepo          *repository.OrderRepository
	checkout           *CheckoutService
	shipping           *ShippingService
	payment            *PaymentService
	emailSender        email.EmailService
	numberGenerator    *ordernumber.Generator
	productCache       ProductCacheInvalidator
	productCacheEvents ProductCacheEventPublisher
}

var (
	ErrOrderNotFound                     = errors.New("order not found")
	ErrOrderDeleteNotAllowed             = errors.New("only cancelled, payment expired, or refunded orders can be deleted")
	ErrSystemManagedOrderStatus          = errors.New("order status is managed by payment workflow")
	ErrTrackingNumberRequired            = errors.New("tracking number is required")
	ErrOrderShippingNotConfigured        = errors.New("order shipping service is not configured")
	ErrOrderNumberNotConfigured          = errors.New("order number generator is not configured")
	ErrOrderItemNotFound                 = errors.New("order item not found")
	ErrDeclaredValueInvalid              = errors.New("declared value must be a finite non-negative number")
	ErrDeclaredValueConfirmationRequired = errors.New("declared value is required when confirming")
)

func NewOrderService(
	txManager *repository.TxManager,
	orderRepo *repository.OrderRepository,
	checkout *CheckoutService,
	shipping *ShippingService,
	numberGenerators ...*ordernumber.Generator,
) *OrderService {
	var numberGenerator *ordernumber.Generator
	if len(numberGenerators) > 0 {
		numberGenerator = numberGenerators[0]
	}
	service := &OrderService{
		txManager:       txManager,
		orderRepo:       orderRepo,
		checkout:        checkout,
		shipping:        shipping,
		numberGenerator: numberGenerator,
	}
	return service
}

func (s *OrderService) ConfigureProductCacheInvalidator(invalidator ProductCacheInvalidator) {
	if s == nil {
		return
	}
	s.productCache = invalidator
}

func (s *OrderService) ConfigureProductCacheEventPublisher(publisher ProductCacheEventPublisher) {
	if s == nil {
		return
	}
	s.productCacheEvents = publisher
}

func (s *OrderService) ConfigurePaymentDisputeAnalysis(payment *PaymentService) {
	if s == nil {
		return
	}
	s.payment = payment
}

func (s *OrderService) ConfigureAdminEmailSender(sender email.EmailService) {
	if s == nil {
		return
	}
	s.emailSender = sender
}

type OrderTrackingUpdateInput struct {
	TrackingNumber     string
	TrackingProviderID uint
	CarrierID          *uint
	CarrierServiceID   *uint
}

func (s *OrderService) GetOrder(id uint, userID uint) (*order.Order, error) {
	o, err := s.orderRepo.FindByID(id)
	if err != nil {
		return nil, normalizeOrderError(err)
	}

	if o.UserID != userID {
		return nil, errors.New("unauthorized")
	}

	return o, nil
}

func (s *OrderService) GetOrderByNumber(orderNumber string, userID uint) (*order.Order, error) {
	if !s.validatesKnownProtectedOrderNumber(orderNumber) {
		return nil, ErrOrderNotFound
	}
	o, err := s.orderRepo.FindByOrderNumber(orderNumber)
	if err != nil {
		return nil, normalizeOrderError(err)
	}

	if o.UserID != userID {
		return nil, errors.New("unauthorized")
	}

	return o, nil
}

// GetOrderByNumberForPayment is intentionally limited to internal payment
// handlers and does not expose a public order-number lookup endpoint.
func (s *OrderService) GetOrderByNumberForPayment(orderNumber string) (*order.Order, error) {
	if !s.validatesKnownProtectedOrderNumber(orderNumber) {
		return nil, ErrOrderNotFound
	}
	o, err := s.orderRepo.FindByOrderNumberForVerification(orderNumber)
	if err != nil {
		return nil, normalizeOrderError(err)
	}
	return o, nil
}

func (s *OrderService) validatesKnownProtectedOrderNumber(value string) bool {
	if ordernumber.IsSequentialCandidate(value) {
		return false
	}
	if !ordernumber.IsProtectedFormat(value) {
		return true
	}
	return s != nil && s.numberGenerator != nil && s.numberGenerator.Validate(value)
}

func (s *OrderService) GetUserOrders(userID uint, page, pageSize int) ([]order.Order, int64, error) {
	return s.orderRepo.FindByUserID(userID, page, pageSize)
}

func (s *OrderService) findOrder(id uint) (*order.Order, error) {
	o, err := s.orderRepo.FindByID(id)
	if err != nil {
		return nil, normalizeOrderError(err)
	}

	return o, nil
}

func (s *OrderService) ProtectedOrderNumberStatus() map[string]interface{} {
	configured := s != nil && s.numberGenerator != nil
	return map[string]interface{}{
		"configured": configured,
		"format":     "TZ-YYYY-<16 char HMAC payload><4 char HMAC checksum>",
		"public_id_policy": []string{
			"Public order numbers are generated by the backend only.",
			"Database auto-increment IDs are not embedded in public order numbers.",
			"Payment gateway merchant order IDs use the public order number.",
		},
		"internal_id_policy": []string{
			"Admin-only routes may still use numeric database IDs after authentication.",
			"Customer-facing routes and chat payloads use order_number only.",
		},
		"verification": "HMAC checksum validation is available for generated order numbers.",
		"key_rotation": "ORDER_NUMBER_PREVIOUS_SECRET may verify old numbers during one rotation window, while new numbers use ORDER_NUMBER_SECRET only.",
	}
}

func normalizeOrderError(err error) error {
	if repository.IsRecordNotFound(err) {
		return ErrOrderNotFound
	}
	return err
}

func (s *OrderService) GetOrderStats(userID uint) (map[string]int64, error) {
	return s.orderRepo.GetOrderStats(userID)
}
